/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_wangchuncheng_HelloWorldJNI */

#ifndef _Included_com_wangchuncheng_HelloWorldJNI
#define _Included_com_wangchuncheng_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangchuncheng_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wangchuncheng_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
